<?php
/** @var \Idea89\Assistant\Block\Widget $block */
if (!$block->shouldRender()) {
    return;
}
?>
<?php /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */ ?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $block->getClientBootstrapJs(), false) ?>
<script
    src="<?= $block->escapeUrl($block->getWidgetUrl()) ?>/widget/v1/<?= $block->escapeUrl($block->getApiKey()) ?>.js"
    data-key="<?= $block->escapeHtmlAttr($block->getApiKey()) ?>"
    data-position="<?= $block->escapeHtmlAttr($block->getWidgetPosition()) ?>"
    async
></script>
